### PR TITLE
Changing the file separater so the root of the DNS zone can be update…

### PR DESCRIPTION
**Pull request by dhowdy**
…d. i.e. @.domain.tld

I've tested this using both relative and absolute paths.  This will free up the "@" symbol so we can update root DNS zones.

### CODE REVIEW

**Comment by dhowdy** [comment]
By the way, I love how this is nice and clean code.  Very very useful. Thanks!

**Comment by NP-Hardass** [comment]
Clever way to fix the problem.  I don't know if @CarlEdman likes it as well, but you might want to also update the @ references to % in the readme in the meantime

**Comment by CarlEdman** [comment]
"@" is kind of traditional for this sort of thing, but if it causes problems for people and changing to another character fixes them, I'm cool with that.

**Comment by arichnad** [comment]
Is there any update on this pull request @CarlEdman ?  Using "@" for this is problematic, and @dhowdy has a great solution to this problem.

**Comment by CarlEdman** [comment]
Sorry for the delay.  All fixed up now.

**Pull request merged**
